### ISSUE TITLE
最新版本客户端检查更新会重复更新当前版本

### ISSUE THREAD

**Issue by Catkamakura** [cyb233/QingShuJia#1]
# Expected Behavior

最新版本点击"**检查更新**"会显示类似“**已是最新版本**”的提示

# Current Behavior

在最新版本（v0.19）中点击"**检查更新**"，点击"**下载最新版本**"，会重复下载当前版本的客户端

# Steps to Reproduce

1. 点击左上角菜单

2. 点击菜单的"**检查更新**"

3. 点击弹出窗口的“**下载最新版本**”按钮

![检查更新](https://noire.cc:233/images/2020/06/23/Screenshot_20200623_0703034c767934ad4d01bd.md.jpg)

**Comment by cyb233** [comment]
这并不冲突，因为这些操作都是手动

**Comment by cyb233** [comment]
判断是否为最新以后可以考虑，目前影响不大

**Comment by cyb233** [comment]
[0.23](https://github.com/cyb233/QingShuJia/releases/tag/0.23)
