### ISSUE TITLE
客户端内下载最新版本的文件无扩展名且不可运行

### ISSUE THREAD

**Issue by Catkamakura** [cyb233/QingShuJia#2]
# Expected Behavior

通过“**检查更新**”下载最新版客户端可安装的apk文件

# Current Behavior
在客户端中点击"**检查更新**"，点击"**下载最新版本**"，会下载无扩展名的不可运行文件

# Steps to Reproduce
1. 点击左上角菜单

2. 点击菜单的"检查更新"

3. 点击弹出窗口的“下载最新版本”按钮

4. 点击下载好的文件“*0524e700-b57f-11ea-904a-28c6f4773a95-2*”

## context

客户端版本：0.19
设备型号：HUAWEI P30
系统版本：EMUI 10.0.0
Android版本：10.0

**Comment by cyb233** [comment]
已修复，手机太聪明有时候反而挺尴尬
