### ISSUE TITLE
Xperia 1 按钮布局有问题

### ISSUE THREAD

**Issue by SquallATF** [cyb233/QingShuJia#6]
![Screenshot_20210506-215006](https://user-images.githubusercontent.com/1386803/117309625-2e0f4b80-aeb5-11eb-9596-e19c0737a05a.png)
另希望提供arm64支持

**Comment by cyb233** [comment]
布局问题还不清楚原因
如果你是指arm64-v8a，这是是ARMv8的指令集，应当也支持armeabi-v7a指令集
如果你是指x86-64，那么确实不支持armeabi-v7a

**Comment by cyb233** [comment]
请确定1.1.0是否解决了布局错误

**Comment by SquallATF** [comment]
已解决
